### ISSUE TITLE
Alignement des éléments graphiques sur la page de garde

### ISSUE THREAD

**Issue by grungi-ankhfire** [emontaigne/site_ecole#1]
Attention, les boutons et les textes ne sont pas toujours bien placés sur la page de garde pour l'instant :D

![image](https://user-images.githubusercontent.com/1303268/94428766-995fa500-0191-11eb-86cc-ad6954bc082d.png)

**Comment by mangbaujessica** [comment]
Hello,
Ca a été changé entre temps. Tout est en ordre :-)
